### ISSUE TITLE
Pushing to FCM isn't working due to typo

### ISSUE THREAD

**Issue by NowAndThen** [malliina/mobile-push#10]
Class GoogleClient has postEndpoint field, but there is using **GcmEndpoint** instead **postEndpoint** in push method. [https://github.com/malliina/mobile-push/blob/master/src/main/scala/com/malliina/push/gcm/GCMClient.scala#L53](url)

**Comment by malliina** [comment]
Hi! Thank you very much for the report. Indeed that is a bug.

I now fixed it so that it correctly uses `postEndpoint` and published a new version `1.19.0` to Maven Central. It should be available within a couple of hours when Maven syncs.
