### ISSUE TITLE
iOS 13 : Need to set apns-push-type in push header

### ISSUE THREAD

**Issue by muskacirca** [malliina/mobile-push#11]
iOS 13 version needs a new header parameter "apns-push-type" to specify if the notification is an alert notification or a background notification :

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

Have you planned an update of your library soon ?

Thank you very much !

**Comment by malliina** [comment]
Hi, thanks for the info. Yes, I plan to add support for that parameter. I will get back to this as soon as there is progress.

**Comment by malliina** [comment]
Hi, I updated the library to version `1.21.0` which now adds the `apns-push-type` header. No API changes should be necessary. I successfully received a notification on my device running iOS 13.1.

The default value is `alert`. I'll try to improve the documentation to clarify how to customize the value in the future.

**Comment by malliina** [comment]
Closing as solved.
