### ISSUE TITLE
java.io.IOException: unexpected end of stream on https://api.push.apple.com/.

### ISSUE THREAD

**Issue by XI808-MridulArora** [malliina/mobile-push#18]
Hey, 

I am facing this issue while sending the notification. I have also included alpn dependency as raised by community on other libraries but doesn't seem to work.

**Comment by malliina** [comment]
Hi, thanks for the report. I'll try to reproduce shortly and will get back to you with results.

**Comment by XI808-MridulArora** [comment]
Hey, thanks for the quick response. I forgot to mention that I am using scala version "2.12.7" and "1.25.0" version of this library.

**Comment by XI808-MridulArora** [comment]
Had a typo in Bundle ID. My bad. :( 
Closing the issue.

**Comment by malliina** [comment]
> Had a typo in Bundle ID. My bad. :( 
> 
> Closing the issue. 

Good to hear! Have a nice day.
