### ISSUE TITLE
Background APNS notifications are not delivered if contain only (content-available=1)

### ISSUE THREAD

**Issue by amogga** [malliina/mobile-push#19]
I was trying to send a background notification with the content-available flag only, but it was not delivered. The request was created as follows:
`APNSRequest.withTopic(<topic>,APNSMessage(APSPayload.background()))`

Although the payload is specified as background, the `APNSPushType` in the meta is still an `alert` type. The problem was fixed by specifying the APNSPushType as `background` in a custom meta configuration and using 
`APNSRequest(APNSMessage(APSPayload.background()),custom_meta)`.

It would be great if APNSPushType comply with APSPayload type and content.

**Comment by malliina** [comment]
Hi! Thanks for the report! I'll investigate and will get back to this. Have a nice day!

**Comment by malliina** [comment]
I committed a fix and released version 3.5.0 to Maven Central right now, it should be available shortly. Again thanks for the report and let me know if there are further issues.

**Comment by malliina** [comment]
I'll close the issue but let me know if the problem persists!
