### ISSUE TITLE
[ERROR] INFO: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?

### ISSUE THREAD

**Issue by MohamedGamaal** [malliina/mobile-push#7]
I got this error when i used APN with Certificate. Here's my code:

  def sendNotification() = {
    val path: Path       = Paths.get("/path/to/cert/certificate.p12")
    val certPass: String = "myCertPass"
    val certKeyStore: KeyStore = TLSUtils.keyStoreFromFile(path, certPass, "PKCS12").get
    val topic = APNSTopic("com.Mcompany.ios")
    val deviceToken: APNSToken = APNSToken.build("my-device-apn-token").get
    val message = APNSMessage.simple("testing")
    val request = APNSRequest.withTopic(topic, message)
    val client = APNSHttpClient(certKeyStore, certPass, isSandbox = true)
    val result: Future[Either[APNSError, APNSIdentifier]] = client.push(deviceToken, request)
    result
  } 

I need your reply ASAP please. Thanks.

**Comment by malliina** [comment]
Hi, you most likely need to have an ALPN jar file on your boot classpath. Please see https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html for details, or `build.sbt` in the root of this repo for an example: https://github.com/malliina/mobile-push/blob/f5e640c49602859ff5ffae7ddfa19ec59c1d0798/build.sbt#L20

**Comment by malliina** [comment]
I'll close due to inactivity.

**Comment by MohamedGamaal** [comment]
@malliina thanks for the reply.
