### ISSUE TITLE
When using APNS [[WARN] [OkHttp ConnectionPool] from okhttp3.OkHttpClient in OkHttp ConnectionPool - A connection to https://api.development.push.apple.com/ was leaked. Did you forget to close a response body] Warning is given

### ISSUE THREAD

**Issue by PraneethAmbegoda** [malliina/mobile-push#8]
As given in the heading a memory leak type of warning is given when trying to connect to APNS. The issue seems to be from the fact that the OkHttp client being not closed properly

**Comment by malliina** [comment]
Thanks for the report. I made some fixes in this area recently. I recommend you try the latest version `1.12.4`. If that version still emits these warnings then I will explore this further.

**Comment by PraneethAmbegoda** [comment]
HI thanks i will have a look and I think this happens only when the external server returns a non 200 status code

**Comment by malliina** [comment]
I'll close this for now and reopen if the warning still occurs.
